trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PackageFeedEndpoint: 'https://pkgs.dev.azure.com/ramiMSFTDevOps/PsRepository/_packaging/PsRepositoryFeed/nuget/v2'
  PackageFeedEndpointCredential: '{"endpointCredentials": [{"endpoint":"$(PackageFeedEndpoint)", "username":"Admin", "password":"$(PsRepoPat)"}]}'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash'

- script: |
    sudo apt-get install -y powershell
  displayName: 'Install PowerShell Core'

- script: |
    # Update the package manager
    sudo apt-get update

    sudo apt-get install -y dotnet-sdk-6.0
    dotnet --version
  displayName: 'Install .NET SDK'

- pwsh: |
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
    Install-Module PowerShellGet -RequiredVersion 2.2.4 -SkipPublisherCheck
    Register-PSRepository -Name "psRepoPipeline" -SourceLocation '$(PackageFeedEndpoint)' -InstallationPolicy Trusted 
  displayName: 'Register Azure Artifacts Feed as PSRepository'
  env:
    VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: $(PackageFeedEndpointCredential)

- pwsh: |
    # List available modules using PowerShellGet
    Get-InstalledModule
  displayName: 'List Available PowerShell Modules'

- pwsh: |
    Find-Module -Name "Get-Hello" | Install-Module -Confirm:$false -Force
  displayName: 'Install the Get-Hello PowerShell module'
  env:
    VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: $(PackageFeedEndpointCredential)
