- stage: deploy
  jobs:
  - deployment: deployWeb
    pool:
      vmimage: 'ubuntu-latest'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Hello World!