trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'DemoTest1'
  displayName: 'DemoTest1'
  jobs: 
    - job: 'Echo1'
      steps:
      - script: echo Hello World!
- stage: 'DemoTest2'
  jobs:
  - deployment: 'DeployToTest'
    environment: 'Test'
    strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Hello World 2!